apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-rolebinding
  namespace: app-namespace
subjects:
- kind: ServiceAccount
  name: viewuser
  namespace: app-namespace
roleRef:
  kind: Role
  name: view-role
  apiGroup: rbac.authorization.k8s.io